#!/usr/bin/with-contenv bash
set -euo pipefail
IFS=$'\n\t'

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

schedule=${SCHEDULE:-'15 0 * * 0'}
args=${ADDITIONAL_ARGS:-}

test -r /config/batch.txt || (echo "/config/batch.txt must exist and contain downloadable URLs" && exit 1)
test -r /config/config.txt || (echo "/config/config.txt must exist and contain youtube-dl config" && exit 1)
test -w "/downloads" || echo "/downloads is not writable, please fix its ownership and/or permissions"


echo '
-------------------------------------
Application setup
-------------------------------------'
echo "
Youtube-dl version:   $(youtube-dl --version)
Python version:       $(python --version 2>&1 | cut -d " " -f 2)
FFMPEG version:       $(ffmpeg -version | head -n 1 | cut -d' ' -f3)
Cron schedule:        ${schedule}
Additional arguments: ${args}
-------------------------------------
"

declare -p | grep -Ev 'BASH|EUID|PPID|SHELLOPTS|UID|YDL_SIGNING_KEY' > /tmp/cron.env
echo -e "SHELL=/bin/bash\nBASH_ENV=/tmp/cron.env\n${schedule} bash /entrypoint.sh ${args}" > /etc/crontabs/abc

# Run first download job right away
bash /entrypoint.sh &

exec crond -f -d 8
